#!/usr/bin/env bash

# monitors
HOSTNAME=$(hostname)
if [[ $HOSTNAME == 'RyzenDev-JS' ]]; then
    MONITOR_MAIN="DisplayPort-0"
    MONITOR_RIGHT="HDMI-A-0"
    xrandr --output $MONITOR_MAIN --primary --auto --output $MONITOR_RIGHT --right-of $MONITOR_MAIN --rotation left
    bspc monitor $MONITOR_MAIN -d 1 2 3 4 5
    bspc monitor $MONITOR_RIGHT -d 6 7 8 9 10
else
    xrandr --auto
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

# bspwm
function xresource() {
    xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | head -n 1
}
COLOR_NORMAL="$(xresource darker)"
COLOR_ACTIVE="$(xresource foreground)"
COLOR_FOCUSED="$(xresource color1)"
COLOR_PRESEL="$(xresource color10)"

bspc config active_border_color $COLOR_ACTIVE
bspc config border_width 2
bspc config border_radius 5
bspc config borderless_monocle false
bspc config focused_border_color $COLOR_FOCUSED
bspc config gapless monocle false
bspc config normal_border_color $COLOR_NORMAL
bspc config presel_feedback_color $COLOR_PRESEL
bspc config split_ratio 0.5
bspc config window_gap 10
 
# autostart
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &
[ -f $HOME/.fehbg ] && $HOME/.fehbg &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x dunst > /dev/null || dunst &
pgrep -x lxpolkit > /dev/null || lxpolkit &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -b --experimental-backends &
pgrep -x unclutter > /dev/null || unclutter &
pgrep -x xautolock > /dev/null || xautolock -time 15 -locker "slock" &
